try {
    // Code that may throw an exception
    const result = 1 / 0;
    console.log(result);
} catch (error) {
    console.error("An error occurred:", error);
}
